export const data = {
    body: [
        { component: "title", text: "Direct Layngoscopy and Intubation" },
        { component: "line" },
        { component: "para", bold: "Materials:", text: "Gloves, appropriately sized blade and ETT, 10mL empty syringe, lubricating gel, lidocaine spray, stethoscope."}, 
        { component: "line" },
        { component: "heading", text: "Sequence" },
        { component: "bullets", text: ["Prepare: Assemble equipment and put on gloves. Check ETT for working light bulb. Check cuff for leaks and prepare a 20mL syringe with air. Add some lubricant to the ETT.", "Position the patient: Tilt head into sniffing position to optimize angles for laryngosco-py. Use scissor finger technique to open mouth. Hold blade in the L hand.", "Advance the blade: Begin blade advancement along the R side of the tongue, which will sweep the tongue leftwards for better visualization. Apply light pressure and con-tinue advancing into the oropharynx until the tip of the epiglottis is visualized. Continue advancement until the blade is in the valleculae.", "Visualize the cords: Apply pressure in the direction of the laryngoscope handle (approx. 45º; keep elbow at side and do not lever the blade on teeth). Directly visualize the cords and note the grade of the view. May apply 1-2 sprays of nebulized lidocaine to cords.", "Intubation: Maintain view of the cords and take the endotracheal tube in the R hand. Insert the tube until the deflated cuff is ~1-2cm past the vocal cords. Inflate the cuff until there is enough air to prevent leakage and avoid tracheal injury from overinflation (may be measured with manometer, ideal 20-30cm H2O).", "Verify for proper placement:"] },
            { component: "bullets", text: ["Stable ETCO2 waveform on capnography", "Direct visualization of ETT between the vocal cords", "Misting of tube on exhalation", "Bilateral breath sounds", "Bilateral chest rise", "X-ray or U/S visualization of ETT (for ICU purposes)"] },
        { component: "line" },
        {component: "para", bold: "Tips for direct laryngoscopy:"},
        { component: "bullets", text: ["If you can’t visualize the epiglottis, the blade may be too deep (in the larynx or   esophagus) or too shallow (at the base of the tongue)", "Ask someone to apply BURP (backwards, upwards, rightwards pressure) to better visualize larynx."] },
        { component: "line" },
        {component: "para", bold: "Troubleshooting:"},
        { component: "bullets", text: ["No ETCO2 / no breath sounds / epigastric gurgling on auscultation: Esophageal intubation", "Unilateral breath sounds/chest rise: ETT may be inserted too far into mainstem bron-chus (i.e. endobronchial intubation)", "Low ETCO2: Check cuff inflation for leaks, kinked tubing, airway obstructions, consider bronchospasm, consider hypotension/low perfusion/cardiac arrest."] },
        { component: "line" },
        {component: "para", bold: "Complications of intubation:"},
        { component: "bullets", text: ["Sore throat", "Airway edema", "Vocal cord paralysis", "Tracheomalacia"] },
        { component: "line" },
        {component: "para", text: "Repeated attempts of intubation can lead to airway trauma and edema, making subsequent attempts more difficult. Plan for your first attempt at intubation to be your best attempt."},
        { component: "line" },
        
        { component: "heading", text: "Elective Induction" },
        {component: "para", bold: "Indications: ", text: "Routine induction (usual risk of aspiration) for elective surgeries in a sufficiently-fasted patient."},
        {component: "para", bold: "Sequence"},
        {component: "para", bold: "1. Prepare: ", text: "Review SOAP IM (page 27) to ensure your supplies are ready. Some import-ant parts are:"},
        { component: "bullets", text: ["Monitors: ensure NIBP is cycled regularly (ex. q1 - 2 min). Ensure other monitors (ECG, pulse ox) have clear readings.", "Airway: ensure circuit is set up for BMV. Test suction and keep within easy reach. Ensure your ETT/SGA and an empty syringe is ready; lubricate and check for proper seal of cuff.", "Machine: APL valve set to zero for bag mask ventilation."] },
        {component: "para", bold: "2. Pre-oxygenation: ", text: "Coach patient through 8 vital capacity breaths with 100% O2, or normal tidal volumes for 3min."},
        {component: "para", bold: "3. Induction + Paralysis: ", text: "Typically begin with a hypnotic agent (e.g. propofol) and an opioid (e.g. fentanyl) to blunt SNS response to laryngoscopy/intubation, followed by a paralytic (e.g. rocuronium or succinylcholine)."},
        {component: "para", bold: "4. BMV: ", text: "When the patient becomes apneic, begin BMV. Increase APL as needed (up to 20 mmHg). Continue until patient is fully paralyzed/optimized for intubation."},
        {component: "para", bold: "5. Intubation: ", text: "Perform laryngoscopy, insert ETT/SGA and inflate cuff."},
        {component: "para", bold: "6. Check: ", text: "Verify the proper placement of the ETT/SGA."},
            { component: "bullets", text: ["Consistent etCO2 waveform", "Misting seen in tube", "Bilateral breath sounds on auscultation"] },
        {component: "para", bold: "7. Secure", text: "Tape the ETT/SGA and ensure patient's eyes are closed and taped."},

        { component: "line" },
        { component: "heading", text: "Rapid Sequence Induction" },
        {component: "para", bold: "Indications: ", text: "Increased risk of aspiration (e.g. unable to protect airway, critically-ill,  pregnant, emergent surgeries, full gastric contents)."},
        {component: "para", bold: "Absolute contraindications: ", text: ""},
        {component: "para", bold: "Sequence: ", text: ""},
        {component: "para", bold: "Prepare: ", text: "Same as Elective Induction sequence above. Prepare other airway equipment as required (e.g. videolarygnoscope, cricothyrotomy kit). Consider pre-induction place-ment of nasogastric tube to drain stomach contents. Position patient sitting upright or 45º if possible until the time of intubation."},
        {component: "para", bold: "Induction + Paralysis: ", text: "IV sedatives (e.g. midazolam, propofol, fentanyl, remifentanyl, or ketamine) followed by immediate IV paralytic (rocuronium or succinylcholine). May ask assistant to apply and maintain cricoid pressure*"},
        {component: "para", bold: "Period of apnea with no BMV awaiting peak paralytic effect", text: "(~30s for succinycholine, ~45s for high-dose rocuronium)"},
        {component: "para", bold: "Intubation", text: "Same as above."},
        {component: "para", bold: "Check", text: "Same as above. If cricoid pressure was used, only instruct for release after ETT placement has been confirmed. "},
        {component: "para", bold: "Secure", text: "Same as above."},
        { component: "line" },
        {component: "para", text: "*Utility of cricoid pressure is controversial and its practice varies by physician. Theoretically, the purpose is to compress the esophagus between the cricoid cartilage and the vertebral bodies, preventing aspiration of gastric contents during induction. However, it may increase the difficulty of laryngoscopy when applied incorrectly."},
        { component: "line" },
        { component: "quiz", question: "", options: [""], answer: "" },
    ]
};